// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygggfrjwrddpigblfowy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlnZ2dmcmp3cmRkcGlnYmxmb3d5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU3MTkyMDMsImV4cCI6MjA2MTI5NTIwM30.eAafDrsDXOJlqO8940KQVTje8BTZjnY4450CiP3NfDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);